### ISSUE TITLE
Installing edge again?

### ISSUE THREAD

**Issue by mryusufcan** [ShadowWhisperer/Remove-MS-Edge#16]
i need to install edge, but it doesn't work in any way, there's just an icon, what should I do?

**Comment by ShadowWhisperer** [comment]
Download it from here

[https://www.microsoft.com/en-us/edge/download?form=MA13FJ](https://www.microsoft.com/en-us/edge/download?form=MA13FJ)

**Comment by jbara2002** [comment]
download the .msi file version of edge
https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ
this will work

**Comment by ShadowWhisperer** [comment]
I'm guessing you already tried rebooting after running the removal tool.

Try deleting this folder **C:\Program Files (x86)\Microsoft\Edge** and running the installer again.

**Comment by ShadowWhisperer** [comment]
Tested both installer versions on multiple machines, Edge installs fine after running this tool. Must be something else blocking it.
