### ISSUE TITLE
Small Sugestions which can be added into the Script

### ISSUE THREAD

**Issue by jbara2002** [ShadowWhisperer/Remove-MS-Edge#18]
## Edge Chromium
`HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}`, delete `experiment_control_labels` if it exists.

Create `HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdateDev` and add the `AllowUninstall` value. This replaces the experiment_control_labels blocker on later versions of Edge Update.

Run uninstall in Settings or Control Panel.

If both WebView2 and Edge Chromium are uninstalled, Microsoft Edge Update will uninstall itself.

## EdgeUWP

Delete `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdge_x.x.x.x_neutral__8wekyb3d8bbwe` (The version will vary depending on your Windows version). This will ensure EdgeUWP is not installed on new accounts.

To remove EdgeUWP on existing accounts, create a key under EndOfLife named the SID of the account that has EdgeUWP, and create a key under that named Microsoft.MicrosoftEdge_8wekyb3d8bbwe. After that, you can use Remove-AppxPackage in powershell to remove. Remove the Microsoft.MicrosoftEdge_8wekyb3d8bbwe key after (**THIS STEP IS IMPORTANT, WINDOWS UPDATE WILL ERROR IF YOU DON'T!**).

And i will put the contents of a powershell script (.ps1 file) there
```
$regView = [Microsoft.Win32.RegistryView]::Registry32
$microsoft = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, $regView).
OpenSubKey('SOFTWARE\Microsoft', $true)

$edgeClient = $microsoft.OpenSubKey('EdgeUpdate\ClientState\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}', $true)
if ($null -ne $edgeClient.GetValue('experiment_control_labels')) {
	$edgeClient.DeleteValue('experiment_control_labels')
}

$microsoft.CreateSubKey('EdgeUpdateDev').SetValue('AllowUninstall', '')

$uninstallRegKey = $microsoft.OpenSubKey('Windows\CurrentVersion\Uninstall\Microsoft Edge')
$uninstallString = $uninstallRegKey.GetValue('UninstallString') + ' --force-uninstall'
Start-Process cmd.exe "/c $uninstallString" -WindowStyle Hidden

$appxStore = '\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore'
$pattern = "HKLM:$appxStore\InboxApplications\Microsoft.MicrosoftEdge_*_neutral__8wekyb3d8bbwe"
$key = (Get-Item -Path $pattern).PSChildName
reg delete "HKLM$appxStore\InboxApplications\$key" /f

$SID = (New-Object System.Security.Principal.NTAccount($env:USERNAME)).Translate([Security.Principal.SecurityIdentifier]).Value

New-Item -Path "HKLM:$appxStore\EndOfLife\$SID\Microsoft.MicrosoftEdge_8wekyb3d8bbwe" -Force

Get-AppxPackage -Name Microsoft.MicrosoftEdge | Remove-AppxPackage

Remove-Item -Path "HKLM:$appxStore\EndOfLife\$SID\Microsoft.MicrosoftEdge_8wekyb3d8bbwe"
```

**Comment by jbara2002** [comment]
__DONT FORGET TO REMOVE THE MICROSOFT EDGE REGISTRY KEY AFTERWARDS OR ELSE YOU WILL WASTE MANY HOURS OF YOUR LIFE FIXING WINDOWS UPDATE!!!!!!!!!!!!__

**Comment by Morku** [comment]
Looks like taken from here: https://gist.github.com/ave9858

**Comment by jbara2002** [comment]
Yes, was taken i've seen as recommandation for this and tested. So i've think can be improvment or something. 
I've working to add a policy to EdgeUpdate which can block futher installation of the EdgeBrowser after is uninstalled with provided script.

**Comment by ShadowWhisperer** [comment]
Both original post and the fist comment are taken word for word from the link @Morku  posted.  Please do not plagiarize.
<br>  


>HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}, delete experiment_control_labels if it exists 

Why not just delete ?: `HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate`
<br>


> HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdateDev

Not much info online pertaining to this. If I ever run into an issue requiring this, I'll look into it. Not going to add If I can't prove it's usefulness.  
<br>

> DONT FORGET TO REMOVE THE MICROSOFT EDGE REGISTRY KEY AFTERWARDS OR ELSE YOU WILL WASTE MANY HOURS OF YOUR LIFE FIXING WINDOWS UPDATE!!!!!!!!!!!!

Posted here: https://gist.github.com/ave9858/c3451d9f452389ac7607c99d45edecc6 with no explanation.

This script was posted: Dec 9, 2020. I used it from a long time before deciding to sharing it. Only issue relating to Windows Update that I've seen is "_KB5006670_" (Oct 2021), which needed Edge installed.  
<br>  

> THIS STEP IS IMPORTANT, WINDOWS UPDATE WILL ERROR IF YOU DON'T!  

I'm pretty certain Windows Update does not do anything with Edge updates. It would EdgeUpdate irrelevant. 
<br>   

> Delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdge_x.x.x.x_neutral__8wekyb3d8bbwe  

I see no reason to delete this. I could spend hours going through and finding all registry keys pertaining to Edge, program them in, and test function; the gain would be nothing. In the past I did... and updates or other random things would stop working or not install properly. Too much of a headache for zero gain. Unless there is a specific reason do delete registry items, it best to just leave it alone.
<br>  

> EdgeUWP  

Removing from other user accounts, I'll look into it when I have more time.

**Comment by jbara2002** [comment]
Understand 😊.
