### ISSUE TITLE
Request for information about the scenario

### ISSUE THREAD

**Issue by kdejeqq** [ShadowWhisperer/Remove-MS-Edge#20]
I would like to know if once Microsoft Edge uninstall this is permanent or the script must be restarted each time?

**Comment by kdejeqq** [comment]
> Après avoir exécuté le script, Edge reste désinstallé.
> 
> *Si vous exécutez Windows 10 et effectuez une mise à niveau vers Windows 11, la mise à niveau installera à nouveau Edge.

Ok and just how do I permanently uninstall
Microsoft Edge WebView2?

**Comment by ShadowWhisperer** [comment]
Run either "_Remove-Edge.exe_" or "_Remove-Edge_GUI.exe_" with **Remove WebView** checked
