### ISSUE TITLE
Console version

### ISSUE THREAD

**Issue by CrypticCus** [ShadowWhisperer/Remove-MS-Edge#21]
Can you please update and make bat file work again? And can you make remove edge or removeedgeonly totally invisible?

**Comment by ShadowWhisperer** [comment]
`Can you please update and make bat file work again?`

The tough part with the .bat version is it needs another .exe file in the same directory as the .bat file. *Not as portable as the standalone .exe versions. It could be done this way:

1. Script runs
2. Checks for setup.exe
        A. check setup.exe hash and compare it to hash saved in .bat
              I. Run uninstaller
             II. Delete setup.exe and go to setup 3
        B. Step 3
3. Check for internet access to github.com
        A. No internet access error
        B. Continue
4. Download _Source/setup.exe file
       A. Error out from download
       B. Continue to set 5
5. Check hash of setup.exe
6. Compare hash of setup.exe with the hash saved in the ,bat file.
     A. If same hash, run
     B. If same hash, delete setup.exe, display hash error

<br>

`Can you make remove edge or removeedgeonly totally invisible?`

If "Remove-Edge.exe" or "Remove-EdgeOnly.exe" are run from cmd, I can add a **/s** flag to make them silent.

**Comment by CrypticCus** [comment]
You need your own setup.exe to complete uninstallation process? Ok then you can save setup.exe as text in the batch file with 

github.com/AveYo/Compressed2TXT

**Comment by CrypticCus** [comment]
also you can try these for uninstalling appx version

>nul powershell -nop -c "Get-WmiObject -Query ' select * from Win32_Product where Name like \"%%MicrosoftEdge%%\" ' | ForEach-Object { ($_).Uninstall()}"
>nul powershell -noprofile -executionpolicy bypass -command "Get-AppxPackage -Name *MicrosoftEdge* -AllUsers | Foreach {Remove-AppxPackage $_.PackageFullName -AllUsers}"
>nul powershell -noprofile -executionpolicy bypass -command "Get-ProvisionedAppxPackage -Online | Where-Object { $_.PackageName -match 'MicrosoftEdge' } | ForEach-Object { Remove-ProvisionedAppxPackage -Online -AllUsers -PackageName $_.PackageName }"

**Comment by ShadowWhisperer** [comment]
`You need your own setup.exe to complete uninstallation process? Ok then you can save setup.exe as text in the batch file with github.com/AveYo/Compressed2TXT`

Yes. The new setup.exe from Microsoft does not work on some systems, so I have to use my own.
Compressed2TXT is interesting, but the extraction is designed to close after extraction, If not, it throws out errors.

base64 could be used but would make the batch file large.

<br>

`also you can try these for uninstalling appx version`
No. Just running a command does not remove Edge appx. Certain reg keys are need to make it uninstall, as show in the python scripts. This part is not an issue with updating the batch script. It's the setup.exe file.

**Comment by CrypticCus** [comment]
Ok then can you send me updated bat file, i will use your setup.exe file

**Comment by CrypticCus** [comment]
Also there is a typo in description

[_Source](https://github.com/ShadowWhisperer/Remove-MS-Edge/tree/main/_Source) contains the python script used in the executable file. [Setup.exe] was pulled from an Edge **intall.**

**Comment by CrypticCus** [comment]
Please update bat file.
