### ISSUE TITLE
Crash exe and GUI

### ISSUE THREAD

**Issue by FastLionArt** [ShadowWhisperer/Remove-MS-Edge#22]
Hello. I just want to remove Edge, but i'm stuck :)
Your new release crashing on my PC. Where is error on screenshot. I downloaded older release, and all removed completely. 
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/130373139/14311149-0139-4d08-9801-e847f319be66)
Thanks for you hard work :)
Have a nice day

**Comment by ShadowWhisperer** [comment]
Thanks!

I **think** I have it fixed.

(-:
