### ISSUE TITLE
GUI crash

### ISSUE THREAD

**Issue by Braizhton** [ShadowWhisperer/Remove-MS-Edge#23]
Hi, still getting an error when executing the GUI :
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/26676447/11e30bd5-0d2e-4fd3-a377-53d182cc28a2)
Thank you, I can't wait to see it work :)

**Comment by ShadowWhisperer** [comment]
By chance, do any of the user names contain special characters, or non A-Z letters?

I updated the GUI to attempt to find what type of encoding the user list is using, before cleaning the user list results. I left the option to show a command windows Please try running the GUI again and posting a screenshot of the command prompt, if the error still shows,

**Comment by Braizhton** [comment]
No special character to my knowledge :/

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/26676447/c05873a1-7661-48a5-9280-387edc1f45cb)

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/26676447/f1eae067-1d62-4f95-82a6-96bc2ca49cc8)
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/26676447/85855fe8-bf2c-4b0e-93ff-795e31381926)

It seems to have worked this time, but there are some errors in the command prompt (in french) that might interest you.

Thanks again
