### ISSUE TITLE
Unhandled exception in script?

### ISSUE THREAD

**Issue by TK50P** [ShadowWhisperer/Remove-MS-Edge#24]
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/127497974/93c949be-a6b0-4cbf-b958-d2da88c9d3f5)

I downloaded latest version of this release, launching speed is so slow, and it shows error
it worked with 6/1/2023 version.

**Comment by ShadowWhisperer** [comment]
Should be fixed, now

**Comment by TK50P** [comment]
Ok, It worked
