### ISSUE TITLE
Leftovers

### ISSUE THREAD

**Issue by Chaython** [ShadowWhisperer/Remove-MS-Edge#25]
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/6486343/67e8a1a8-689b-4301-b5c0-5dda460b44e0)
Both of these packages are still in registry

**Comment by ShadowWhisperer** [comment]
What version of Windows?
Where does it list those?
Did you try rebooting after running?

**Comment by Chaython** [comment]
Yes, I see them in simplewall. Normally after uninstalling a windows store app, it will show as a random numerical combination. 
For example, here are the uninstalled edge components.
![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/6486343/96164a7a-ee01-4078-961e-b8ea303a4811)
But these edge components still exist
Microsoft.MicrosoftEdge_40.15063.0.0_neutral__8wekyb3d8bbwe.xml
Seems related to many built in apps
But it seems Microsoft.MicrosoftEdgeDevToolsClient_1000.22621.1.0_neutral_neutral_8wekyb3d8bbwe is related to appinstaller?

**Comment by ShadowWhisperer** [comment]
It should be working again

**Comment by Chaython** [comment]
Yes, it removed those two packages 

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/6486343/97773cc2-7061-4cbd-9abe-0f5429c99bbf)
