### ISSUE TITLE
suggestion: delete cache files

### ISSUE THREAD

**Issue by bre97-web** [ShadowWhisperer/Remove-MS-Edge#27]
After the edge update, there will be Temp and EdgeUpdate folders under the Microsoft folder, I think these files **should be deleted**.

- EdgeUpdate
- Temp

**Comment by ShadowWhisperer** [comment]
Added.

**EdgeUpdate** does not always uninstall like it is supposed to. Sometimes the folder disappears a minute or so after the tool is ran.
