### ISSUE TITLE
Remove-EdgeOnly Flag Not Working As Intended

### ISSUE THREAD

**Issue by ceticdev** [ShadowWhisperer/Remove-MS-Edge#28]
Hello, I have been trying to add this to a few machines I work on that do not need Edge installed. 

Task Scheduler will run the program when any user logs on using admin permissions and I have the /s flag in the arguments box. However, when testing this after a user logs on a command prompt will open and still display the 'Uninstalling Edge' text. 

My intended effect is that the user logs on and the process will run in the background with no new tabs or text displayed. Is this functionality possible or am I missing a setting? 

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/43022787/bd4b39fd-904c-4140-8cac-32ed9236a900)

**Comment by ShadowWhisperer** [comment]
It has to do with how the program is compiled. I uploaded a new file **NoTerm.exe**. It does not remove EdgeView, does not show the terminal, and does not need flags. Just run it.

Be sure to check the "_Run with highest privileges_"

![Capture](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/61057625/a9e18f9a-3576-4f97-af9b-619e7a2ed722)

**Comment by ceticdev** [comment]
You're amazing. Thanks a bunch!

**Comment by ShadowWhisperer** [comment]
You are welcome!
