### ISSUE TITLE
keep getting error in gui

### ISSUE THREAD

**Issue by PitchAbyss** [ShadowWhisperer/Remove-MS-Edge#29]
i cannot run any gui app to uninstall on win 11

![image](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/13099434/da964239-5497-45d3-9e81-b72dc7405b44)

**Comment by ShadowWhisperer** [comment]
Tested on 3 Windows 11 machines today, and working. Unable to reproduce message.

Looks like Windows Defender is probably blocking it. Turn off Defender and it will work. *I've seen this error before on systems that users have done improper removal of Windows Defender.  Usually under  **reputation-based protection**

**Comment by PitchAbyss** [comment]
> Tested on 3 Windows 11 machines today, and working. Unable to reproduce message.
> 
> Looks like Windows Defender is probably blocking it. Turn off Defender and it will work. *I've seen this error before on systems that users have done improper removal of Windows Defender.  Usually under  **reputation-based protection**

But my system doesnt have defender i have removed it allready

**Comment by ShadowWhisperer** [comment]
In my experience, unless you make a custom image with [NTLite](https://www.ntlite.com/), trying to remove it causes problems. Best to just disable it with [Defender Control](https://www.sordum.org/9480/defender-control-v2-1/). Windows updates messes with Defender, even if it's "removed" from the computer.

Try enabling it again with "_Defender Control_" and see if Defender will open, to manually turn off **reputation-based protection**. If Defender still will not open, I do not know of a fix for a partially removed Defender.

**Comment by PitchAbyss** [comment]
> In my experience, unless you make a custom image with [NTLite](https://www.ntlite.com/), trying to remove it causes problems. Best to just disable it with [Defender Control](https://www.sordum.org/9480/defender-control-v2-1/). Windows updates messes with Defender, even if it's "removed" from the computer.
> 
> Try running "_Defender Control_". Enable Defender, then click disable Defender. Run Edge removal tool.
> 
> If that does not work, enable Defender, and turn off **reputation-based protection**. If Defender still will not open, I do not know of a fix for a partially removed Defender.

Ohhk thanks will try and yes its via ntlite

**Comment by ShadowWhisperer** [comment]
Could also try this in cmd

```
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v EnableWebContentEvaluation /t REG_DWORD /d 0
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v EnableSmartScreen /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v ContentEvaluation /t REG_DWORD /d 0 /f
```

**Comment by PitchAbyss** [comment]
> Could also try this in cmd, then reboot
> 
> ```
> reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v EnableWebContentEvaluation /t REG_DWORD /d 0
> reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v EnableSmartScreen /t REG_DWORD /d 0 /f
> reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f
> reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v ContentEvaluation /t REG_DWORD /d 0 /f
> ```

hi i did run and reboot

![Screenshot_1](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/13099434/e628529e-639e-4a43-9b3b-0663a9785965)

**Comment by ShadowWhisperer** [comment]
Guessing that it still won't run?

**Comment by PitchAbyss** [comment]
> Guessing that it still won't run?
> 

Yes it dint :(

**Comment by ShadowWhisperer** [comment]
You could try this batch script. Old script I made to Disable Windows Defender. Requires a reboot. Not sure if it still works.


```
@echo off

cls & echo. & echo Killing Processes
::Processes
taskkill /im "SecurityHealthService.exe" /f /t >nul 2>&1
taskkill /im "SecurityHealthSystray.exe" /f /t >nul 2>&1
taskkill /im "smartscreen.exe" /f /t >nul 2>&1
::
taskkill /im "SecurityHealthService.exe" /f /t >nul 2>&1
taskkill /im "SecurityHealthSystray.exe" /f /t >nul 2>&1
taskkill /im "smartscreen.exe" /f /t >nul 2>&1
::Services
echo - Services
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WinDefend" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\Sense" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\SecurityHealthService" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisDrv" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisSvc" /v Start /t REG_DWORD /d 4 /f >nul 2>&1

::Tasks
echo - Tasks
takeown /F "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" /A /R >nul 2>&1
icacls "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" /grant administrators:F /T >nul 2>&1
rmdir /s/q "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" >nul 2>&1

echo - Settings
::Disable Windows Defender, Cloud-based protection, and Automatic Sample Submission
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableBehaviorMonitoring /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableOnAccessProtection /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableScanOnRealtimeEnable /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet" /v SubmitSamplesConsent /t REG_DWORD /d 0 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows Defender\Spynet" /v "SpyNetReporting" /t REG_DWORD /d 0 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows Defender\Spynet" /v "SubmitSamplesConsent" /t REG_DWORD /d 0 /f >nul 2>&1
::SmartScreen
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v EnableSmartScreen /t REG_DWORD /d 0 /f >nul 2>&1

```

**Comment by PitchAbyss** [comment]
> You could try this batch script. Old script I made to Disable Windows Defender. Requires a reboot. Not sure if it still works.
> 
> ```
> @echo off
> 
> cls & echo. & echo Killing Processes
> ::Processes
> taskkill /im "SecurityHealthService.exe" /f /t >nul 2>&1
> taskkill /im "SecurityHealthSystray.exe" /f /t >nul 2>&1
> taskkill /im "smartscreen.exe" /f /t >nul 2>&1
> ::
> taskkill /im "SecurityHealthService.exe" /f /t >nul 2>&1
> taskkill /im "SecurityHealthSystray.exe" /f /t >nul 2>&1
> taskkill /im "smartscreen.exe" /f /t >nul 2>&1
> ::Services
> echo - Services
> reg add "HKLM\SYSTEM\CurrentControlSet\Services\WinDefend" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
> reg add "HKLM\SYSTEM\CurrentControlSet\Services\Sense" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
> reg add "HKLM\SYSTEM\CurrentControlSet\Services\SecurityHealthService" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
> reg add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisDrv" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
> reg add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisSvc" /v Start /t REG_DWORD /d 4 /f >nul 2>&1
> 
> ::Tasks
> echo - Tasks
> takeown /F "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" /A /R >nul 2>&1
> icacls "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" /grant administrators:F /T >nul 2>&1
> rmdir /s/q "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender" >nul 2>&1
> 
> echo - Settings
> ::Disable Windows Defender, Cloud-based protection, and Automatic Sample Submission
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /t REG_DWORD /d 1 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableBehaviorMonitoring /t REG_DWORD /d 1 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableOnAccessProtection /t REG_DWORD /d 1 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" /v DisableScanOnRealtimeEnable /t REG_DWORD /d 1 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet" /v SubmitSamplesConsent /t REG_DWORD /d 0 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Microsoft\Windows Defender\Spynet" /v "SpyNetReporting" /t REG_DWORD /d 0 /f >nul 2>&1
> reg add "HKLM\SOFTWARE\Microsoft\Windows Defender\Spynet" /v "SubmitSamplesConsent" /t REG_DWORD /d 0 /f >nul 2>&1
> ::SmartScreen
> reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v EnableSmartScreen /t REG_DWORD /d 0 /f >nul 2>&1
> ```

this i think is for defender not edge

**Comment by ShadowWhisperer** [comment]
Correct. The original error you are getting is from **Smart Screen**, part of **Defender**

**Comment by PitchAbyss** [comment]
> Correct. The original error you are getting is from **Smart Screen**, part of **Defender**

still same :(

**Comment by toasteddpotato** [comment]
@PitchAbyss Just in case you made the same mistake I did:

You cannot right-click the hyperlinked .exe and "Save as." You need to click the .exe and "View Raw." That will download the full executable. 

When I did "save as" I got the same exact Smart Screen popup.

**Comment by PitchAbyss** [comment]
> @PitchAbyss Just in case you made the same mistake I did:
> 
> You cannot right-click the hyperlinked .exe and "Save as." You need to click the .exe and "View Raw." That will download the full executable.
> 
> When I did "save as" I got the same exact Smart Screen popup.

this my sir has made it work ....so thannkyou my friend amazing

**Comment by ShadowWhisperer** [comment]
@toasteddpotato

Appreciate your help!
Added to the readme, notes
