### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by seba2282** [ShadowWhisperer/Remove-MS-Edge#30]
Only Edge and Gui with uncheck WebView, make to remove all than edge without WebView.

**Comment by ShadowWhisperer** [comment]
If I understand correctly, **Remove-EdgeOnly.exe** is removing _WebView_, is that correct?

**Comment by seba2282** [comment]
That i told. The same no term and gui, when we have unchecked WebView.

**Comment by seba2282** [comment]
> Remove-EdgeOnly.exe

I see some fix for Remove only edge. What about remove edge gui, which after uncheck about WebView, he still remove WebView. I reported few. I test edge only remove now if work finally. But you need look and that second too ;)

**Comment by seba2282** [comment]
So i tested updated and only edge delete still webwiev. Example in windows 11 in virtual machine. And that gui, when is unchecked WebView, still remove WebView. I don't know if it is good or not. But after update edge only is removed edge update. So to complete. Gui and and that normal edge removal let's stay only update edge still. You can look too on that? ;)

**Comment by ShadowWhisperer** [comment]
Looks like Microsoft changed something. Looking into it.

**Comment by seba2282** [comment]
Thanks for informations :)

**Comment by ShadowWhisperer** [comment]
Fixed. It was an error on my end. Should be working now.
* Sorry for the long delay, I was down with the flew.

**Comment by seba2282** [comment]
So Only Edge and that gui, when uncheck WebView, shouldn't now remove WebView, if i understood good. I let's me then test that on virtual machine. Tomorrow after work, I take tests and i will write if all good. Thanks for answers :)

**Comment by ShadowWhisperer** [comment]
Thank you for bringing it to my attention!
