### ISSUE TITLE
Removing Edge conflicts with Windows updates?

### ISSUE THREAD

**Issue by angelog0** [ShadowWhisperer/Remove-MS-Edge#34]
Just for completeness ...

I had use RemoveEdge and now I am facing with an issue with Windows updates. After flagging the issue to Microsoft [community](https://answers.microsoft.com/en-us/windows/forum/all/how-to-install-update-kb5031445/f0337f87-fbf9-422a-9ec6-783789a926a3), someone there responded that if one has uninstalled Edge this browser should be reinstalled...

What do you thing about this?

**Comment by ShadowWhisperer** [comment]
Thanks for the note!

I have not seen this issue.... yet. It's very possible that a new update may cause problems. I head about some "big" update coming out, but didn't look much into it.

If I do see this, I'll make a note in the Readme. I have links in the Readme to install Edge again.

This tool does not prevent Edge from re-installing. Install Edge, run the update, and remove Edge again.
I saw issues with updates back in 2021 for **KB5006670**

**Comment by angelog0** [comment]
I will try and report..

**Comment by angelog0** [comment]
Ok, with Edge installed the update installs.. Maybe we can close this..

**Comment by ShadowWhisperer** [comment]
Added to the Readme.

Thanks for the information!
