### ISSUE TITLE
Currently there is another webview 2 runtime in my windows

### ISSUE THREAD

**Issue by ReadChart** [ShadowWhisperer/Remove-MS-Edge#39]
Edition	Windows 11 Pro
Version	23H2
Installed on	‎6/‎17/‎2023
OS build	22631.2792
Experience	Windows Feature Experience Pack 1000.22681.1000.0
Location: C:\Windows\WinSxS\amd64_microsoft-edge-webview_<removed_hash>_10.0.22621.2506_none_<removed_hash>
Which also contains msedgewebview2.exe

**Comment by ShadowWhisperer** [comment]
From what I've seen, _WebView2_ does not come pre-installled, and is removable from the programs and features list.

#33 ` C:\Windows\WinSxS\FileMaps\*edge* is deletable, but anything else in that folder, is not.`

**Comment by FadeMind** [comment]
@ShadowWhisperer 
Your app removing WebView2 **even** when I disabled opt for remiving WebView2.
After using `MicrosoftEdgeWebview2Setup.exe` need to be repaired whole install via setting option in UWP Setting App WebView2 settings.
Also task scheduler entries were gone after cleanup via Your tool AND does not recovery after use `MicrosoftEdgeWebview2Setup.exe`. I can create separate issue if you like.

Windows 11 23H2 22631.2861

Funny thing:
![20231215-1702666926](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/9846948/d78258f8-3af4-4c17-a661-86e52cf80088)
![20231215-1702666890](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/9846948/801f98e8-f709-412a-a3db-bfdb2aaac691)

**Comment by ShadowWhisperer** [comment]
If **Edge is installed** - WebView2 installs to `C:\Program Files (x86)\Microsoft\Edge`
 If **Edge is not installed** - WebView2 installs to `C:\Program Files (x86)\Microsoft\EdgeWebView`
 
 To keep WebView2 working, WebView2 has to be uninstalled before running this tool, and then re-installed
 
 The edge uninstaller (setup.exe) removes `C:\Program Files (x86)\Microsoft\Edge`
