### ISSUE TITLE
DON'T DOWNLOAD THE EXECUTABLES IN THE README, THEY ARE VIRUSES!

### ISSUE THREAD

**Issue by spacesweedkid-27** [ShadowWhisperer/Remove-MS-Edge#41]
Firefox and Windows flag the executables as viruses, after running one, a Windows Defender notification pops up and tells me that it installed a Trojan.
To be specific, the "Trojan:Win32/Wacatac.B!ml" is recognized which, if untreated, can cause data leaks.

**Comment by jomixlaf** [comment]
lol

**Comment by ShadowWhisperer** [comment]
False positive. Already been discussed. Chrome uses Windows Defender to scan for "malware"
Readme links are links to the files listed above.....

https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/11
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/40

**Comment by spacesweedkid-27** [comment]
Ok thanks, maybe add a notice to the README so that new users don't get sudden anxiety :P
