### ISSUE TITLE
This is now considered "malware".

### ISSUE THREAD

**Issue by 480ScratchGithub** [ShadowWhisperer/Remove-MS-Edge#42]
Most of the files automatically get removed by MSD and have WacatacA!ml. Half of Virustotal was showing similar results: https://www.virustotal.com/gui/file/133e3f8325f5bb9a3d0fbafa2c03ab88b433b51911338339646599cb228d7595/detection

<img width="524" alt="susus2" src="https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/119143348/09ee37e6-bd72-4819-a74f-95c176ac944b">
<img width="949" alt="susus1" src="https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/119143348/bbae28ff-8729-466b-89ce-2689c80c9b16">

**Comment by ShadowWhisperer** [comment]
Has been for a while

https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/11
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/41
https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/40
