### ISSUE TITLE
add C:\Windows\System32\Microsoft-Edge-WebView\

### ISSUE THREAD

**Issue by grandpa1946** [ShadowWhisperer/Remove-MS-Edge#44]
title says it all
i could do it myself, but i get some requirements errors and don't want to install an older version of python/...

**Comment by grandpa1946** [comment]
i mean that it is also possible that there is a webview2 install without an installer

**Comment by theraininsky** [comment]
God edge is everywhere

**Comment by usefulstuffs** [comment]
I think this is for UWP apps and it might break them but I'm not sure.

**Comment by ShadowWhisperer** [comment]
I haven't found much on this folder, either.

Don't want to break anything
It took Microsoft 2 months to scan this to prove it's not malware. Any time I update, it will need to be reviewed.

**Comment by grandpa1946** [comment]
yeah microsoft has weird av software

**Comment by ShadowWhisperer** [comment]
Due to how prevalent WebView is, I'm going to leave it in tact.
I've worked on a number of systems that require it, and it's not worth the headache trying to figure out why some software does not work.
