### ISSUE TITLE
2024-4-13它已经无法运行了，以管理员权限运行也没有反应

### ISSUE THREAD

**Issue by qingye32149** [ShadowWhisperer/Remove-MS-Edge#49]
今天（也可能是昨天晚上）我的电脑自动重启了，它给我自动安装了新版本的edge，我尝试使用这个程序发现它无法运行了，并且geek unin和unintool都无法卸载edge

**Comment by ShadowWhisperer** [comment]
我明天会在工作时查看

**Comment by ShadowWhisperer** [comment]
你正在使用哪个版本的Windows？我一直在努力重现这个问题。

**Comment by qingye32149** [comment]
对不起大大，让您久等了，因为不怎么看邮件也不怎么登GitHub[捂脸]
这是我的系统版本：
设备名称	DESKTOP-MB6AIF0
处理器	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
机带 RAM	4.00 GB (3.86 GB 可用)
设备 ID	F2F21F55-5093-429F-8351-0F125C837763
产品 ID	00342-35060-76634-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2021/‎4/‎24
操作系统内部版本	19045.3930
体验	Windows Feature Experience Pack 1000.19053.1000.0


现在的情况是edge浏览器从我的开始--磁贴那里消失了，但是
![1710831601(1)](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/117875431/0ff25d58-bd4a-4bf8-a5f8-2a6a64397eb2)
在设置-应用里面还是有，而且蛮大[哭哭]

**Comment by eebssk1** [comment]
大版本更新是会给你装回来的，需要添加注册表opt-out。或者自己用uupdump做个系统iso，创建选项有个有关edge的值改成2

**Comment by ShadowWhisperer** [comment]
工具已转换回批处理脚本。请再试一次，然后告诉我。

Tool has been converted back to batch scripts. Try again, and let me know.
