### ISSUE TITLE
Edge Update 无法被卸载

### ISSUE THREAD

**Issue by lokvahkooravidya** [ShadowWhisperer/Remove-MS-Edge#53]
错误日志如下：

Removing Edge Update
Remove-AppxPackage : 不支持该请求。
错误 0x80070032: C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe 中的程序包 Microsoft.Microso
ftEdgeDevToolsClient_1000.22621.1.0_neutral_neutral_8wekyb3d8bbwe 上的 AppX 部署 Remove 操作失败。此应用是 Windows 的一
部分，无法针对每个用户卸载该应用。管理员可以尝试使用“启用或关闭 Windows 功能”从计算机中删除该应用。不过，该应用可能无
法被卸载。
所在位置 行:1 字符: 1
+ Remove-AppxPackage -Package Microsoft.MicrosoftEdgeDevToolsClient_100 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

Windows 版本如下：
版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎1/‎5
操作系统版本	22631.3447
体验	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by ShadowWhisperer** [comment]
工具已转换回批处理脚本。请再试一次，然后告诉我。

Tool has been converted back to batch scripts. Try again, and let me know.

**Comment by lokvahkooravidya** [comment]
> 工具已转换回批处理脚本。请再试一次，然后告诉我。
> 
> 工具已转换回批处理脚本。再试一次，然后告诉我。

问题已经被解决
