### ISSUE TITLE
webview detection fail

### ISSUE THREAD

**Issue by eebssk1** [ShadowWhisperer/Remove-MS-Edge#54]
`# Edge Update - Remaining
subprocess.run(['reg', 'delete', r'HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate', '/f'], startupinfo=hide_console(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)`
This should not do if keep webview,otherwise many application uses webview will not be able to  detect installed webview and ask you to install it.

**Comment by eebssk1** [comment]
FYI. The reg key records the installation path of the system wide webview.

**Comment by ShadowWhisperer** [comment]
You are correct. Broke the Xbox app, when testing.

Specifically
`HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}\` pv

This will be omitted from the next update.

Thanks!

**Comment by ShadowWhisperer** [comment]
Should be working.
Removal tool has been converted to a batch script, due to how long it takes to report false positives to AV software, every time there is an update.

**Comment by eebssk1** [comment]
Try implementing a c# one and test it with AV? 
I was using it in OOBE which does not have network yet,though I can place the setup.exe along with the bat.
