### ISSUE TITLE
why do you insist on removing exe files?

### ISSUE THREAD

**Issue by allahin** [ShadowWhisperer/Remove-MS-Edge#55]
bat files don't fully work, files don't download, even if I download and throw them away I get --uninstall not found error. even if you don't recommend exe files it's insane to uninstall them completely.

**Comment by ShadowWhisperer** [comment]
Too may complainants of false malware.

Exe are still at [Link](https://github.com/ShadowWhisperer/Remove-MS-Edge/tree/main/Retired)

**Comment by ShadowWhisperer** [comment]
Too many people complaining about false positives for malware.
* Exe files were moved to the Retired folder.
Made a folder batch, and moved the .exe back to where they were

**Comment by allahin** [comment]
Thanks for bringing back the exe files. closing the thread.
