### ISSUE TITLE
MicrosoftEdgeDevToolsClient cannot be removed

### ISSUE THREAD

**Issue by Morpheus1123** [ShadowWhisperer/Remove-MS-Edge#56]
Disable defender and run Remove-Edge_GUI.exe as admin, click "Remove".
After I do this, restart my computer, do it again, it appears again.
![A](https://github.com/ShadowWhisperer/Remove-MS-Edge/assets/37213889/b68c0c5a-784e-4ffa-b1e8-3397cff60104)
(Forgive the blurry screenshot...)

Removing Appx Packages
Microsoft.MicrosoftEdgeDevToolsClient_1000...........

Windows 10 LTSC 2021, the latest version.

Thanks for your software.

**Comment by Morpheus1123** [comment]
This information may be useful.

Get-AppxPackage *edge*

Name              : Microsoft.MicrosoftEdgeDevToolsClient
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : Neutral
ResourceId        : neutral
Version           : 1000.19041.4239.0
PackageFullName   : Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe
InstallLocation   :
IsFramework       : False
PackageFamilyName : Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : True
IsPartiallyStaged : False
SignatureKind     : System
Status            : Ok

Remove-AppxPackage -Package 'Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe' -AllUsers

Remove-AppxPackage : 不支持该请求。
错误 0x80070032: C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe 中的程序包 Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe 上的 AppX 部署 Remove 操作失败。此应用是 Windows 的一部分，无
法针对每个用户卸载该应用。管理员可以尝试使用“启用或关闭 Windows 功能”从计算机中删除该应用。不过，该应用可能无法被卸载。
所在位置 行:1 字符: 1
+ Remove-AppxPackage -Package 'Microsoft.MicrosoftEdgeDevToolsClient_10 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand

**Comment by ShadowWhisperer** [comment]
I have not been able to duplicate this error
