### ISSUE TITLE
Missing sanity checks before programming tasks.

### ISSUE THREAD

**Issue by I2pRandom** [ShadowWhisperer/Remove-MS-Edge#58]
The script is missing a sanity check before doing tasks such as deleting the Icon.
This is an edge case, I had already forcibly removed Edge before. But need to fully clean up the fact edge existed, to reinstall webview functionality for an App. So the script throws an error because some things are Already missing. 
```python
D:\000SystemUsers\JasonPanic\Desktop>Remove-NoTerm.exe
Traceback (most recent call last):
  File "edge.py", line 33, in <module>
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\JASONP~1\AppData\Local\Temp\_MEI122002/icon.ico" not defined
[5292] Failed to execute script 'edge' due to unhandled exception!

D:\000SystemUsers\JasonPanic\Desktop>
```

**Comment by ShadowWhisperer** [comment]
Should be fixed. Issue with how the program is converted.
