### ISSUE TITLE
How to Reinstall edge after script use?

### ISSUE THREAD

**Issue by Quiescent51** [ShadowWhisperer/Remove-MS-Edge#60]
Hey there, to put it shortly I need edge to be able to play minecraft and any method I use to try and reinstall it fails. I would greatly appreciate any kind of help. The reinstall edge links in code page just seem to silently fail after running. Also the microsoft store tells me Edge is still installed in case that info is of any use.

**Comment by ShadowWhisperer** [comment]
I haven't been able to reproduce issues with re-installing Edge, after removing. Did you run/do something before this tools, to try and remove edge?

The [Small-DL](https://www.microsoft.com/en-us/edge/download?form=MA13FJ) link will say it is already installed. (Microsoft assumes nobody removed it) Click the **continue to download edge** in blue, under the _Open Edge_ button.
