### ISSUE TITLE
Remove-AppxPackage : The request is not supported.

### ISSUE THREAD

**Issue by I2pRandom** [ShadowWhisperer/Remove-MS-Edge#62]
C:\Users\JasonPanic\Downloads>Remove-Edge.exe
Removing Edge Update                                                                                                    Remove-AppxPackage : The request is not supported.
error 0x80070032: AppX Deployment Remove operation on package
Microsoft.MicrosoftEdgeDevToolsClient_1000.22621.1.0_neutral_neutral_8wekyb3d8bbwe from:
C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe failed. This app is part of Windows and
cannot be uninstalled on a per-user basis. An administrator can attempt to remove the app from the computer using Turn
Windows Features on or off. However, it may not be possible to uninstall the app.
At line:1 char:1
+ Remove-AppxPackage -Package Microsoft.MicrosoftEdgeDevToolsClient_100 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

**Comment by ShadowWhisperer** [comment]
I've seen this on a couple of systems. It should still remove Edge.

Is your Windows a modified install ? (Custom ISO)
Have you tried other removal tools/manual removal attempts ?

**Comment by lingjiamian** [comment]
it occured when i run on win11 24h2

**Comment by chaptsand** [comment]
I have same error on official LTSC 2021
But edge actually removed

**Comment by chaptsand** [comment]
```NonRemovable           : True```
```
Name                   : Microsoft.MicrosoftEdgeDevToolsClient
Publisher              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture           : Neutral
ResourceId             : neutral
Version                : 1000.19041.4239.0
PackageFullName        : Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe
InstallLocation        : 
IsFramework            : False
PackageFamilyName      : Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe
PublisherId            : 8wekyb3d8bbwe
PackageUserInformation : {S-1-5-21-368602865-242250755-2804464961-1001 [Chaptsand]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : True
IsPartiallyStaged      : False
SignatureKind          : System
Status                 : Ok
```
