### ISSUE TITLE
keep Webview without Edge Core and Edge Updater

### ISSUE THREAD

**Issue by Andarwinux** [ShadowWhisperer/Remove-MS-Edge#66]
The variant that keep Webview looks like it will also keep Edge Updater, is there a variant that only keep Webview without Edge Core and Edge Updater?

**Comment by ShadowWhisperer** [comment]
Looks like Edge Update is used by WebView.

Brought WebView removal back - [Remove-EdgeWeb.exe](https://github.com/ShadowWhisperer/Remove-MS-Edge/blob/main/Remove-EdgeWeb.exe?raw=true)
