### ISSUE TITLE
Webview is required for the Photos app edit function

### ISSUE THREAD

**Issue by thepcwiz1012** [ShadowWhisperer/Remove-MS-Edge#68]
I found this out after removing both edge and webview. The app will crash without it. Reinstalling webview is the only way to fix it.

**Comment by thepcwiz1012** [comment]
Also this will be useful for those who need to reinstall webview: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by ShadowWhisperer** [comment]
Added, thanks!
