### ISSUE TITLE
what is the setup.exe?

### ISSUE THREAD

**Issue by TommyCowley101** [ShadowWhisperer/Remove-MS-Edge#72]
this inst an issue but just wondered what the setup.exe exactly is? as i thought it was just the downloader for edge but after downloading the setup file directly from Microsoft and trying to use it with your batch file it don't seem to work and gives a error

**Comment by ShadowWhisperer** [comment]
In the older versions of Edge it was possible to uninstall it with command line instructions. The setup.exe file was in the Edge folder, after it was installed. At some point Microsoft modified this setup file, so Edge could not be removed. The provided setup.exe file is the older version that still allows the uninstall.

**Comment by Tmalll** [comment]
Does anyone know from which version Microsoft banned the use of setup.exe to uninstall Edge?

**Comment by ShadowWhisperer** [comment]
@Tmalll

> I suspect Microsoft pushed out an Edge update between 2022-May and 2022-Oct which caused the removal script to stop working. Another script also stopped working that used to work for Win 10 Pro 21H2.

https://github.com/ShadowWhisperer/Remove-MS-Edge/issues/9#issuecomment-1314637708
