### ISSUE TITLE
[REQ] Add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [ShadowWhisperer/Remove-MS-Edge#75]
Hi there, 1st of all thanks for this awesome work !

Since I've 'doxed' it in the [TWEAKERS page](https://github.com/MarcoRavich/Opendows/blob/main/Tweakers.md#-) of the [Opendows project](https://forart.it/opendows), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/ShadowWhisperer/Remove-MS-Edge)
(badge-generator URL: https://badgen.net/github/license/ShadowWhisperer/Remove-MS-Edge)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, I invite you to join [CS Discussions](https://github.com/mewostick/Creosynth/discussions) to share ideas about Windows tweakings.

Hope that helps/inspires !

**Comment by ShadowWhisperer** [comment]
Added

**Comment by MarcoRavich** [comment]
Cool, thanks, it works now !
