### ISSUE TITLE
can't remove Edge-WebView from System32

### ISSUE THREAD

**Issue by cisko99za** [ShadowWhisperer/Remove-MS-Edge#77]
tried your wonderful tool Remove-EdgeWeb.exe on my win 11 24H2 x64 and work fine, but missing uninstall Edge-WebView folder (with all files, about 500MB) from C:\Windows\System32\Microsoft-Edge-WebView

**Comment by ShadowWhisperer** [comment]
`C:\Windows\System32\Microsoft-Edge-WebView` is WebView2

** Different from WebView, and removable from 'Program & Features'

**Comment by cisko99za** [comment]
ah ok. thanks for clarification
